- name: Read users from CSV
  community.general.read_csv:
    path: "{{ role_path }}/files/users.csv"
  delegate_to: localhost
  register: users_list

- name: Create groups
  ansible.builtin.group:
    name: "{{ item.group }}"
    state: present
  loop: "{{ users_list.list }}"
  become: true
  become_user: root

- name: Create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: "{{ item.group }}"
    create_home: yes
    shell: /bin/bash
    state: present
  loop: "{{ users_list.list }}"
  become: true
  become_user: root

- name: Set authorized keys
  ansible.builtin.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_key }}"
    state: present
  loop: "{{ users_list.list }}"
  become: true
