- name: Add Prometheus as Grafana datasource
  community.grafana.grafana_datasource:
    name: Prometheus
    type: prometheus
    url: http://localhost:9090
    access: proxy
    is_default: yes
    state: present

