---
- name: Deploy Monitoring Stack
  hosts: all
  become: yes
  roles:
    - node_exporter

- name: Deploy Prometheus and Grafana
  hosts: monitoring
  become: yes
  vars:
    grafana_admin_user: admin
    grafana_admin_password: admin
  roles:
    - prometheus
    - grafana
