---
- name: Setup SSH keys and server on PnetLab containers
  hosts: all
  become: true
  gather_facts: false

  vars:
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:

    - name: Ensure .ssh directory exists
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: Copy public key to authorized_keys
      copy:
        content: "{{ ssh_pub_key }}"
        dest: /root/.ssh/authorized_keys
        mode: '0600'

    - name: Install SSH server (openssh-server)
      package:
        name: openssh-server
        state: present

    - name: Ensure SSH service is started
      service:
        name: ssh
        state: started
        enabled: yes

